apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker3
spec:
  image: strimzi/kafka-mirror-maker:latest
  replicas: 1
  consumer:
    bootstrapServers: my-cluster-kafka-bootstrap:9092
    groupId: my-source-group-id
  producer:
    bootstrapServers: my-cluster-mtarget-kafka-bootstrap:9092
  whitelist: "my-topic"